services:
  # 训练服务 - 16GB内存优化配置
  train:
    image: chatglm-cpu-trainer
    container_name: chatglm-train
    volumes:
      - ./data:/app/data
      - ./models:/app/models
    environment:
      - OMP_NUM_THREADS=8
      - MKL_NUM_THREADS=8
      - HF_ENDPOINT=https://hf-mirror.com
      - PYTHONPATH=/app
    command: python -m app.train 
              --model_name_or_path THUDM/chatglm2-6b 
              --dataset_path /app/data/input/dataset.txt 
              --output_dir /app/models/chatglm-lora
              --quantization 8bit
              --max_seq_length 128
              --max_samples 800
              --lora_r 16
              --per_device_train_batch_size 2
              --gradient_accumulation_steps 8
              --learning_rate 5e-5
              --num_train_epochs 3
    deploy:
      resources:
        limits:
          memory: 15G
    restart: "no"

  # 预测服务
  predict:
    image: chatglm-cpu-trainer
    container_name: chatglm-predict
    volumes:
      - ./data:/app/data
      - ./models:/app/models
    environment:
      - OMP_NUM_THREADS=8
      - MKL_NUM_THREADS=8
      - HF_ENDPOINT=https://hf-mirror.com
      - PYTHONPATH=/app
    command: python -m app.predict
              --model_path /app/models/chatglm-lora
              --base_model_path THUDM/chatglm2-6b
              --quantization 8bit
              --prompt "请介绍一下人工智能的发展历史。"
              --max_length 2048
    deploy:
      resources:
        limits:
          memory: 15G
    restart: "no"